spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/champions_league_prono
spring.datasource.username=prono_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

jwt.secret=your-secret-key
jwt.expiration=86400000

soccerdata.api.key=${SOCCERDATA_API_KEY}